/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tateti;

import java.awt.Color;
/**
 *
 * @author German Medina https://github.com/germanchopp
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        load();
        scoreX.setBackground(Color.LIGHT_GRAY);
        scoreO.setBackground(Color.LIGHT_GRAY);
        leftVertical.setVisible(false);
        centerVertical.setVisible(false);
        rightVertical.setVisible(false);
        topHorizontal.setVisible(false);
        mediumHorizontal.setVisible(false);
        bottomHorizontal.setVisible(false);
        diagonal1.setVisible(false);
        diagonal2.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        playAgain = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        diagonal1 = new javax.swing.JLabel();
        diagonal2 = new javax.swing.JLabel();
        topHorizontal = new javax.swing.JLabel();
        mediumHorizontal = new javax.swing.JLabel();
        bottomHorizontal = new javax.swing.JLabel();
        leftVertical = new javax.swing.JLabel();
        centerVertical = new javax.swing.JLabel();
        rightVertical = new javax.swing.JLabel();
        b00 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scoreX = new javax.swing.JPanel();
        xPlayer = new javax.swing.JLabel();
        pX = new javax.swing.JLabel();
        scoreO = new javax.swing.JPanel();
        oPlayer = new javax.swing.JLabel();
        pO = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h1.setFont(new java.awt.Font("Pixel Operator Mono 8", 3, 22)); // NOI18N
        h1.setForeground(java.awt.Color.orange);
        h1.setText(" SPACE TATETI ");
        h1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, null));
        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 40, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spaceship.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 39, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 59, -1, -1));

        playAgain.setBackground(java.awt.Color.orange);
        playAgain.setFont(new java.awt.Font("Pixel Operator HB 8", 1, 18)); // NOI18N
        playAgain.setForeground(java.awt.Color.darkGray);
        playAgain.setText("PLAY AGAIN");
        playAgain.setAlignmentY(5.0F);
        playAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainActionPerformed(evt);
            }
        });
        getContentPane().add(playAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 220, 50));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        diagonal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dia1.png"))); // NOI18N
        jPanel1.add(diagonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        diagonal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dia2.png"))); // NOI18N
        jPanel1.add(diagonal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        topHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horizontal.png"))); // NOI18N
        jPanel1.add(topHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        mediumHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horizontal.png"))); // NOI18N
        jPanel1.add(mediumHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        bottomHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/horizontal.png"))); // NOI18N
        jPanel1.add(bottomHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, -1, -1));

        leftVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        jPanel1.add(leftVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        centerVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        jPanel1.add(centerVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        rightVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        jPanel1.add(rightVertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 10, -1, -1));

        b00.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b00ActionPerformed(evt);
            }
        });
        jPanel1.add(b00, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, 100));

        b01.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b01ActionPerformed(evt);
            }
        });
        jPanel1.add(b01, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 6, 100, 100));

        b02.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b02ActionPerformed(evt);
            }
        });
        jPanel1.add(b02, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 6, 100, 100));

        b10.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 100, 100));

        b11.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel1.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 112, 100, 100));

        b12.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel1.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 112, 100, 100));

        b20.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });
        jPanel1.add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, 100, 100));

        b21.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        jPanel1.add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 218, 100, 100));

        b22.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 24)); // NOI18N
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        jPanel1.add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 218, 100, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 324, 324));

        xPlayer.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 36)); // NOI18N
        xPlayer.setForeground(java.awt.Color.red);
        xPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xPlayer.setText("X");

        pX.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 36)); // NOI18N
        pX.setForeground(java.awt.Color.red);
        pX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pX.setText("0");

        javax.swing.GroupLayout scoreXLayout = new javax.swing.GroupLayout(scoreX);
        scoreX.setLayout(scoreXLayout);
        scoreXLayout.setHorizontalGroup(
            scoreXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreXLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(xPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(pX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        scoreXLayout.setVerticalGroup(
            scoreXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreXLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(scoreXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xPlayer)
                    .addComponent(pX))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        oPlayer.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 36)); // NOI18N
        oPlayer.setForeground(java.awt.Color.blue);
        oPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oPlayer.setText("O");

        pO.setFont(new java.awt.Font("Pixel Operator Mono 8", 1, 36)); // NOI18N
        pO.setForeground(java.awt.Color.blue);
        pO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pO.setText("0");

        javax.swing.GroupLayout scoreOLayout = new javax.swing.GroupLayout(scoreO);
        scoreO.setLayout(scoreOLayout);
        scoreOLayout.setHorizontalGroup(
            scoreOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreOLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(oPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(pO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        scoreOLayout.setVerticalGroup(
            scoreOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoreOLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(scoreOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oPlayer)
                    .addComponent(pO))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(scoreX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scoreO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 220, 260));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int matrix [][] = new int [3][3];
public void load(){
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            matrix [i][j] = (j+10) * (i+10);
            
        }
        
    }
}

LogicGame lG = new LogicGame(0, 0, 0);

public void shiftChange (){
    if(lG.getTurn()==1){
        scoreX.setBackground(Color.YELLOW);
        scoreO.setBackground(Color.LIGHT_GRAY);            
    }
    if(lG.getTurn()==0){
        scoreX.setBackground(Color.LIGHT_GRAY);
        scoreO.setBackground(Color.YELLOW);            
    }

}

public void reboot(){
    load();
    b00.setText("");
    b00.setEnabled(true);
    b01.setText("");
    b01.setEnabled(true);
    b02.setText("");
    b02.setEnabled(true);
    b10.setText("");
    b10.setEnabled(true);
    b11.setText("");
    b11.setEnabled(true);
    b12.setText("");
    b12.setEnabled(true);
    b20.setText("");
    b20.setEnabled(true);
    b21.setText("");
    b21.setEnabled(true);
    b22.setText("");
    b22.setEnabled(true);
    leftVertical.setVisible(false);
    centerVertical.setVisible(false);
    rightVertical.setVisible(false);
    topHorizontal.setVisible(false);
    mediumHorizontal.setVisible(false);
    bottomHorizontal.setVisible(false);
    diagonal1.setVisible(false);
    diagonal2.setVisible(false);
   
    

}

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix,leftVertical, 4, 2, 0);
        lG.scratch(matrix, bottomHorizontal, 3, 2, 0);
        lG.scratch(matrix,diagonal2, 8, 2, 0);
        if(lG.play(b20, 2, 0, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b20ActionPerformed

    private void b00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b00ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix, diagonal1, 7, 0, 0);
        lG.scratch(matrix,topHorizontal, 1, 0, 0);
        lG.scratch(matrix,leftVertical, 4, 0, 0);
        if(lG.play(b00, 0, 0, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b00ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix,leftVertical, 4, 1, 0);
        lG.scratch(matrix, mediumHorizontal, 2, 1, 0);
        if(lG.play(b10, 1, 0, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b01ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix, topHorizontal, 1, 0, 1);
        lG.scratch(matrix, centerVertical, 5, 0, 1);
        if (lG.play(b01, 0, 1, matrix, pX, pO) == 1) {
            reboot();
        }
    }//GEN-LAST:event_b01ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix, diagonal1, 7, 1, 1);
        lG.scratch(matrix, centerVertical, 5, 1, 1);
        lG.scratch(matrix, mediumHorizontal, 2, 1, 1);
        lG.scratch(matrix,diagonal2, 8, 1, 1);
        if(lG.play(b11, 1, 1, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix,centerVertical, 5, 2, 1);
        lG.scratch(matrix, bottomHorizontal, 3, 2, 1);
        if(lG.play(b21, 2, 1, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b21ActionPerformed

    private void b02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b02ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix,topHorizontal, 1, 0, 2);
        lG.scratch(matrix,rightVertical, 6, 0, 2);
        lG.scratch(matrix,diagonal2, 8, 0, 2);
        if(lG.play(b02, 0, 2, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b02ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix,rightVertical, 6, 1, 2);
        lG.scratch(matrix, mediumHorizontal, 2, 1, 2);
        if(lG.play(b12, 1, 2, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
        shiftChange();
        lG.scratch(matrix, diagonal1, 7, 2, 2);
        lG.scratch(matrix,rightVertical, 6, 2, 2);
        lG.scratch(matrix, bottomHorizontal, 3, 2, 2);
        if(lG.play(b22, 2, 2, matrix, pX, pO)==1){
            reboot();        
        }
    }//GEN-LAST:event_b22ActionPerformed

    private void playAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainActionPerformed
        // TODO add your handling code here:
        reboot();
        lG.resetScore();
        
        pX.setText(Integer.toString(lG.getsX()));
        pO.setText(Integer.toString(lG.getsX()));
        
    }//GEN-LAST:event_playAgainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b00;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bottomHorizontal;
    private javax.swing.JLabel centerVertical;
    private javax.swing.JLabel diagonal1;
    private javax.swing.JLabel diagonal2;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel leftVertical;
    private javax.swing.JLabel mediumHorizontal;
    private javax.swing.JLabel oPlayer;
    private javax.swing.JLabel pO;
    private javax.swing.JLabel pX;
    private javax.swing.JButton playAgain;
    private javax.swing.JLabel rightVertical;
    private javax.swing.JPanel scoreO;
    private javax.swing.JPanel scoreX;
    private javax.swing.JLabel topHorizontal;
    private javax.swing.JLabel xPlayer;
    // End of variables declaration//GEN-END:variables
}
